#!/usr/bin/env python3
"""RP-04: rank/entropy of Toeplitz 127×127 low-convolution map for fixed top."""
from __future__ import annotations

import hashlib
import json
import random
import statistics
from collections import Counter
from pathlib import Path

OUT = Path(r"archive/legacy-probes/rp-04/rp04_toep_map_rank.json")
EFF = 127


def gf2_rank_rows(rows: list[int], ncols: int = EFF) -> int:
    basis = {}
    rank = 0
    for row in rows:
        r = row
        while r:
            c = (r & -r).bit_length() - 1
            if c >= ncols:
                r ^= 1 << c
                continue
            piv = basis.get(c)
            if piv is None:
                basis[c] = r
                rank += 1
                break
            r ^= piv
    return rank


def toep_matrix_from_top(top_bits: int) -> list[int]:
    """out[j] = sum_{i=0..j} y[i] * top[j-i]  (GF2). Column i of map is top shifted by i, truncated to 127."""
    # row j, col i (i<=j): top[j-i]
    rows = []
    for j in range(EFF):
        row = 0
        for i in range(j + 1):
            if (top_bits >> (j - i)) & 1:
                row |= 1 << i
        rows.append(row)
    return rows


def first_set_bit(top_bits: int) -> int:
    if top_bits == 0:
        return EFF  # none
    return (top_bits & -top_bits).bit_length() - 1


def predicted_rank(top_bits: int) -> int:
    """Lower-triangular Toeplitz: rank = 127 - v where v = valuation = first set bit of top.
    If top=0, rank=0. If first set bit at position k, first k output coeffs are always 0 for any y
    when... actually out[j] for j < k depends only on top[0..j] which are 0 ⇒ out[j]=0.
    Map image dimension = 127 - k for nonzero top with valuation k.
    Also if higher structure? For pure lower-triangular Toeplitz generated by top, rank is
    127 - val(top) when top != 0, else 0.
    """
    if top_bits == 0:
        return 0
    k = first_set_bit(top_bits)
    return EFF - k


def apply_map(top_bits: int, y_bits: int) -> int:
    out = 0
    for j in range(EFF):
        acc = 0
        for i in range(j + 1):
            acc ^= ((y_bits >> i) & 1) & ((top_bits >> (j - i)) & 1)
        if acc:
            out |= 1 << j
    return out


def main():
    rng = random.Random(0x5151)
    ranks = []
    vals = []
    formula_match = 0
    N = 2000
    for _ in range(N):
        top = rng.getrandbits(EFF)
        rows = toep_matrix_from_top(top)
        r = gf2_rank_rows(rows)
        pred = predicted_rank(top)
        ranks.append(r)
        vals.append(first_set_bit(top) if top else EFF)
        if r == pred:
            formula_match += 1

    # Differential basis check: for random top, flip y e_i and collect columns
    diff_ok = 0
    for _ in range(50):
        top = rng.getrandbits(EFF)
        cols = []
        for i in range(EFF):
            cols.append(apply_map(top, 1 << i))
        # rank of columns
        r = gf2_rank_rows(cols)
        if r == predicted_rank(top):
            diff_ok += 1

    # Active-like: AES-generated top low 127 bits — model as uniform random
    # histogram
    hist = Counter(ranks)
    val_hist = Counter(vals)

    # three independent cores product: each core is hash_to_fp_nonzero(lo,hi) of 127-bit
    # map degeneracy on y doesn't give public constraint without top (keyed)

    report = {
        "probe": "RP-04",
        "eff_bits": EFF,
        "samples": N,
        "rank_histogram": {str(k): hist[k] for k in sorted(hist)},
        "min_rank": min(ranks),
        "max_rank": max(ranks),
        "mean_rank": statistics.mean(ranks),
        "full_rank_rate": sum(1 for r in ranks if r == EFF) / N,
        "first_set_bit_histogram_head": {str(k): val_hist[k] for k in sorted(val_hist)[:20]},
        "formula": "rank = 0 if top==0 else 127 - valuation(top)",
        "formula_vs_gaussian_match": formula_match / N,
        "differential_basis_match_rate": diff_ok / 50,
        "random_top_expectation": {
            "P(val>=k)": "2^{-k} approx for uniform top",
            "E[rank]": "127 - sum_{k>=1} P(val>=k) ≈ 127 - 1 = 126 for nonzero; incl zero tiny",
            "observed_mean_rank": statistics.mean(ranks),
        },
        "three_core_product": (
            "Each R-core = hash_to_fp(toep(top,y)); independent tops per domain. "
            "Even if one map has rank 126, product R1*R2*R3 in Fp still looks uniform nonzero; "
            "no public core outputs to enforce linear constraints on y."
        ),
        "verdict": "CLOSED",
        "close_reason": (
            "Rank follows random-top expectation (mean ~126, full-rank rate ~50%); "
            "degeneracy is valuation-driven, not a stable secret-independent kernel; "
            "no public R-core; three-core product erases usable linear constraints."
        ),
        "applicability_to_active": (
            "Active tops are AES-CTR keyed by prf_k — unknown. Map degeneracy cannot be "
            "exploited without top. QP-02 already proved only 127 bits of y matter; RP-04 shows "
            "those 127 bits are essentially full-rank into the 127-bit toep output."
        ),
    }
    OUT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))
    print("sha256", hashlib.sha256(OUT.read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
